np数组以及对应的函数
https://www.numpy.org.cn/reference/

In [34]:
import numpy as np

# 1. 数组的创建。 将列表传入参数
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr)
print(type(arr))

print('数组形状：', '行：' , arr.shape[0], '列：', arr.shape[1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
数组形状： 行： 2 列： 5


In [35]:
# 2. 索引和切片
print(arr[1])
print(arr[0:1])
print(arr[:, 1:2])

[ 6  7  8  9 10]
[[1 2 3 4 5]]
[[2]
 [7]]


In [36]:
# 3. 计算(+-*/都是对应元素进行运算)
print('列表运算：',[1, 2, 3] + [4, 5, 6])
print('数组运算：', np.array([1, 2, 3]) + np.array([4, 5, 6]))
print('*:' , np.array([1, 2, 3]) * np.array([4, 5, 6]))

列表运算： [1, 2, 3, 4, 5, 6]
数组运算： [5 7 9]
*: [ 4 10 18]


In [37]:
# 4. 数组形状操作
print(arr.shape)
arr1 = arr.reshape(5, 2)
print(arr1, '新的数组形状是：', arr1.shape)
print(arr1.transpose()) # 转置

(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 新的数组形状是： (5, 2)
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [38]:
#5. 线性代数, 统计
arr1 = np.array([1, 2, 3])
arr2 = np.array([7, 5, 6])
print('arr1:', arr1, 'arr2:', arr2)
print('点乘：', np.dot(arr1, arr2))
print('arr1的平均值：', arr1.mean())
print('标准差：', np.std(arr1))
print('排序：', np.sort(arr2))
print(arr2>6) # 对应位置分别比较，可用于进行筛选
print(arr2[(arr2>6) & (arr2<10)])

arr1: [1 2 3] arr2: [7 5 6]
点乘： 35
arr1的平均值： 2.0
标准差： 0.816496580927726
排序： [5 6 7]
[ True False False]
[7]


In [39]:
#6. 数据的保存与导入
np.save('arr', arr1)
arr = np.load('arr.npy')
print(arr)

[1 2 3]
